Small improvements for better use
mpl-extensions/mpl-point-clicker pull request #17
Opened 2024-01-10 11:37 UTC by Xraydylan

Changes:
- Made `classes` an optional argument with the default class being "1"

Added:
- `disable_legend` argument to optionally not display classes in legend
- `clear_positions()` function to remove all points from a class (or all classes) with external call

2024-01-10 11:38 UTC, Xraydylan commented
Note:
I haven't made changes to the doc so far

2024-01-12 20:07 UTC, ianhi requested changes
Hi @Xraydylan thanks for this PR! This is going to be a great change, to my surprise it seems that most people use this library with only one class.

I've requested some coding changes below but looking good to start

2024-01-12 20:07 UTC, ianhi commented on mpl_point_clicker/_clicker.py
> +            disable_legend = False
```suggestion
```

I understand the urge here - but we shouldn't override the user input here. They may be changing the current class programmatically or with their own gui elements. Also with `disable_legend` default to False we don't need to check for `None`

2024-01-12 20:07 UTC, ianhi commented on mpl_point_clicker/_clicker.py
> +            disable_legend = True
Move this below where we turn `classes` into a list so we can check the length and thus have a more robust check

```suggestion
        if len(classes) == 1) and disable_legend is None:
            disable_legend = True
```

2024-01-12 20:08 UTC, ianhi commented
the docs build is not your fault. I have an outdated config file that readthedocs finally stopped supporting. I'll fix that in a separate PR

2024-01-23 19:20 UTC, merged

2024-01-23 19:21 UTC, ianhi commented
Thank you for the contribution @Xraydylan ! You are actually the first contributor outside of me for this repo :) I really appreciate you taking the time to do this work